### ISSUE TITLE
Docker compose with cli (feat request)

### ISSUE THREAD

**Issue by unleashit** [Dokploy/cli#5]
Would be really nice to be able to add docker compose setups with the cli with something like `dokploy compose`. In some cases having to connect a git repo is not desirable. Also would be great to configure a domain. Either through cli commands or possibly have it read a config file.

Bottom line is it would be great to eventually be able to configure things as declaratively as possible.

**Comment by pepijnolivier** [comment]
I too would like to be able to fully automate a pipeline.

In one bash script, I would like to be able to:

- Create a new project
- Create a new application in that project
- Attach the application to a subdomain (of which I have a wildcard DNS setting): `auto-deploy-001.example.com`
- Automatically set letsencrypt certificates (as the UI already allows)
- Upload a Dockerfile by passing a file path
- Receive back an info message about the state of my application (status: deploying,/ url: endpoint, ...)

**Comment by amustapha** [comment]
> I too would like to be able to fully automate a pipeline.
> 
> In one bash script, I would like to be able to:
> 
> * Create a new project
> * Create a new application in that project
> * Attach the application to a subdomain (of which I have a wildcard DNS setting): `deploy-001.deployments.example.com`
> * Automatically set letsencrypt certificates (as the UI already allows)
> * Upload a Dockerfile by passing a local file path
> * Upsert environment variables by passing in a local file path to an `.env` file
> * Receive back an info message about the state of my application (status: deploying,/ url: endpoint, ...)

exactly what brought me here. I think i'll create a PR to allow this to support yaml files

**Comment by Siumauricio** [comment]
Closed — resolved in the CLI rewrite (#36). The CLI now supports all 28 compose commands auto-generated from the OpenAPI spec, including `dokploy compose create`, `dokploy compose deploy`, `dokploy compose update`, and more. Run `dokploy compose --help` to see all available actions.

**Comment by pepijnolivier** [comment]
@Siumauricio 

Thanks for tagging a new version 🙏 
Just one thing, when I pull the latest version and then run "dokploy --version", it still shows 0.3.0 (instead of 0.3.1)
I think it's due to it being hardcoded here: 
https://github.com/Dokploy/cli/blob/main/src/index.ts

---

It likely needs a version bump there whenever a new tag is created.
